### ISSUE TITLE
Caltrans EAC Presentation Meta-Issue

### ISSUE THREAD

**Issue by jkarpen** [cagov/caldata-mdsa-caltrans-pems#26]
- [ ] Gather Requirements for EAC Presentation #47 
- [ ] Develop presentation for EAC #48 
- [ ] Shop around to Caltrans leadership? TBD, ask Said if necessary
- [ ] Give Presentation to EAC (no issue needed for this)

The actual presentation will be in Mid-March, exact date not scheduled yet.

**Comment by jkarpen** [comment]
Moving this to backlog for now as this might not be needed. Will move back into a sprint if we end up needing it later.

**Comment by jkarpen** [comment]
@jasonlally @ian-r-rose Closing this one as I believe the EAC presentation is no longer needed.
