### ISSUE TITLE
Template: MDSA training kick off checklist

### ISSUE THREAD

**Issue by britt-allen** [cagov/caldata-mdsa-caltrans-pems#43]
We need a check list to keep us organized for when we kick off MDSA trainings
Things we always need to do are...

- [x] Collect data on which staff will receive which training
- [x] Create a github repo and team
- [x] Collect all github usernames
- [x] Work with IT OPs to get all GitHub users added to our organization
- [x] Create a dbt account without SSO (this is done by dbt)
- [x] Invite all users to dbt
- [x] Create a snowflake account
- [x] Create a Snowflake username and password and individually send to all users
- [x] Edit Snowflake training content
- [x] Edit dbt training content
- [x] Edit kick off deck
- [x] Edit Git/GitHub training content
- [x] Edit training progress tracker
- [x] Create one pre-training skill assessment survey
- [x] Create one post-training skill assessment survey
- [x] Create one training feedback survey
- [x] Check what we committed to adding or improving in our retro
- [x] Schedule all the training sessions and office hours sessions in advance. (One 2-hour block for the kick off, One 2-hour block for Git/GitHub, Two 2-hour blocks for Snowflake, Four 2-hour blocks for dbt, 1-hour, optional, office hours blocks in between each day)

**Comment by britt-allen** [comment]
I'll turn this into a doc! For now if I am missing something feel free to comment it to the thread

**Comment by britt-allen** [comment]
This can be reused for future MDSA projects @jkarpen
