### ISSUE TITLE
Meta-issue: PeMS detector health diagnostics

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/caldata-mdsa-caltrans-pems#85]
Meta issue for all PeMS health diagnostics:

- [x] #78 (blocked by config file work) @britt-allen
- [x] #79 @britt-allen 
- [x] #80 @kengodleskidot 
- [x] #81 @kengodleskidot 
- [x] #82 @kengodleskidot 
- [x] #83 (Blocked by imputation logic)
- [x] #84 (Blocked and related to #79)

**Comment by britt-allen** [comment]
I will be bringing in two seed tables or macros for detector type and
diagnostic threshold set mapping that are dependencies for the issues above.
